Repository remarkjs/react-markdown, pull requests merged in 2020-10, with the labels that each got.

#486 Move demo to `website` branch
  .eslintignore
  .gitignore
  .prettierignore
  demo/dist/css/demo.css
  demo/dist/index.html
  demo/dist/js/demo.js
  demo/src/code-block.js
  demo/src/codemirror.js
  demo/src/demo.js
  demo/src/editor.js
  demo/src/markdown-controls.js
  package.json
  rollup.config.demo.js
  rollup.config.js
  umd/.gitkeep
Labels: 🏡 area/internal, 🙆 status/confirmed

#485 Rewrite readme for unified, more examples
  CHANGELOG.md
  README.md
  changelog.md
  license
  package.json
  readme.md
  test/__snapshots__/react-markdown.test.js.snap
  test/react-markdown.test.js
Labels: 👩‍⚕ area/health, 📚 area/docs, 🙆 status/confirmed, 🦋 type/enhancement

#487 Refactor and test for 100% coverage
  .travis.yml
  src/ast-to-react.js
  src/get-definitions.js
  src/plugins/disallow-node.js
  src/plugins/html-parser.js
  src/react-markdown.js
  src/renderers.js
  src/symbols.js
  test/react-markdown.test.js
Labels: 🕸️ area/tests, 🗄 area/interface, 🙆 status/confirmed, 🦋 type/enhancement

#490 test(types): add dtslint tests to verify typescript typings
  index.d.ts
  package.json
  react-markdown-types-test.tsx
  tsconfig.json
  tslint.json
  with-html.d.ts
Labels: ☂️ area/types, 🧒 semver/minor
