Repository remarkjs/react-markdown, pull requests merged in 2021-04, with the labels that each got.

#563 Replace `renderers` w/ `components`, remove HTML parser from core
  index.d.ts
  package.json
  plugins/html-parser.js
  react-markdown-types-test.tsx
  readme.md
  src/ast-to-react.js
  src/get-definitions.js
  src/plugins/html-parser.js
  src/react-markdown.js
  src/rehype-filter.js
  src/remark-filter-nodes.js
  src/remark-parse-html.js
  src/remark-wrap-table-rows.js
  src/renderers.js
  src/with-html.js
  test/__snapshots__/react-markdown.test.js.snap
  test/fixtures/runthrough.md
  test/react-markdown.test.js
  tsconfig.json
  with-html.d.ts
  with-html.js
Labels: 🗄 area/interface, 🙆 status/confirmed, 🦋 type/enhancement, 🧑 semver/major

#566 Add JSDoc based types
  .gitignore
  index.d.ts
  package.json
  src/ast-to-react.js
  src/react-markdown.js
  src/rehype-filter.js
  src/uri-transformer.js
  test/react-markdown.test.js
  tsconfig.json
Labels: ☂️ area/types, 🔍 status/open, 🦋 type/enhancement

#567 Update changelog for v6
  changelog.md
  package.json
  src/react-markdown.js
  test/react-markdown.test.js
Labels: 📚 area/docs

#572 xo
  package.json
  src/ast-to-react.js
  src/react-markdown.js
  src/rehype-filter.js
  src/uri-transformer.js
  test/react-markdown.test.js
Labels: 🏗 area/tools

#571 Remove compiled library
  .eslintignore
  .gitignore
  .prettierignore
  package.json
Labels: 🏗 area/tools

#578 Add architecture section to readme
  readme.md
Labels: 📚 area/docs
